/**
 * WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetListRequestConfigListItemDto } from './get-list-request-config-list-item-dto';


export interface GetListRequestConfigListItemDtoGetListResponse { 
    index?: number;
    size?: number;
    count?: number;
    pages?: number;
    hasPrevious?: boolean;
    hasNext?: boolean;
    items?: Array<GetListRequestConfigListItemDto> | null;
}

