/**
 * WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginForControllerDto } from '../model/models';
import { RegisterForControllerDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiAuthLoginPostRequestParams {
    loginForControllerDto?: LoginForControllerDto;
}

export interface ApiAuthRegisterPostRequestParams {
    registerForControllerDto?: RegisterForControllerDto;
}

export interface ApiAuthRevokeTokenPutRequestParams {
    body?: string;
}

export interface ApiAuthVerifyEmailAuthenticatorGetRequestParams {
    activationKey?: string;
}

export interface ApiAuthVerifyOtpAuthenticatorPostRequestParams {
    body?: string;
}


export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiAuthEnableEmailAuthenticatorGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    apiAuthEnableOtpAuthenticatorGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiAuthLoginPost(requestParameters: ApiAuthLoginPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    apiAuthRefreshTokenGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiAuthRegisterPost(requestParameters: ApiAuthRegisterPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiAuthRevokeTokenPut(requestParameters: ApiAuthRevokeTokenPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiAuthVerifyEmailAuthenticatorGet(requestParameters: ApiAuthVerifyEmailAuthenticatorGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiAuthVerifyOtpAuthenticatorPost(requestParameters: ApiAuthVerifyOtpAuthenticatorPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
