/**
 * WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateRequestOperationClaimsCommand } from '../model/models';
import { UpdateRequestOperationClaimsCommand } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiRequestOperationClaimsGetRequestParams {
    pageIndex?: number;
    pageSize?: number;
}

export interface ApiRequestOperationClaimsIdDeleteRequestParams {
    id: string;
}

export interface ApiRequestOperationClaimsIdGetRequestParams {
    id: string;
}

export interface ApiRequestOperationClaimsPostRequestParams {
    createRequestOperationClaimsCommand?: CreateRequestOperationClaimsCommand;
}

export interface ApiRequestOperationClaimsPutRequestParams {
    updateRequestOperationClaimsCommand?: UpdateRequestOperationClaimsCommand;
}


export interface RequestOperationClaimsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRequestOperationClaimsGet(requestParameters: ApiRequestOperationClaimsGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRequestOperationClaimsIdDelete(requestParameters: ApiRequestOperationClaimsIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRequestOperationClaimsIdGet(requestParameters: ApiRequestOperationClaimsIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRequestOperationClaimsPost(requestParameters: ApiRequestOperationClaimsPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRequestOperationClaimsPut(requestParameters: ApiRequestOperationClaimsPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
