/**
 * WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserOperationClaimCommand } from '../model/models';
import { DeleteUserOperationClaimCommand } from '../model/models';
import { UpdateUserOperationClaimCommand } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiUserOperationClaimsDeleteRequestParams {
    deleteUserOperationClaimCommand?: DeleteUserOperationClaimCommand;
}

export interface ApiUserOperationClaimsGetRequestParams {
    pageIndex?: number;
    pageSize?: number;
}

export interface ApiUserOperationClaimsIdGetRequestParams {
    id: string;
}

export interface ApiUserOperationClaimsPostRequestParams {
    createUserOperationClaimCommand?: CreateUserOperationClaimCommand;
}

export interface ApiUserOperationClaimsPutRequestParams {
    updateUserOperationClaimCommand?: UpdateUserOperationClaimCommand;
}


export interface UserOperationClaimsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUserOperationClaimsDelete(requestParameters: ApiUserOperationClaimsDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUserOperationClaimsGet(requestParameters: ApiUserOperationClaimsGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUserOperationClaimsIdGet(requestParameters: ApiUserOperationClaimsIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUserOperationClaimsPost(requestParameters: ApiUserOperationClaimsPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUserOperationClaimsPut(requestParameters: ApiUserOperationClaimsPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
