/**
 * WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserCommand } from '../model/models';
import { DeleteUserCommand } from '../model/models';
import { UpdateUserCommand } from '../model/models';
import { UpdateUserFromAuthCommand } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiUsersDeleteRequestParams {
    deleteUserCommand?: DeleteUserCommand;
}

export interface ApiUsersFromAuthPutRequestParams {
    updateUserFromAuthCommand?: UpdateUserFromAuthCommand;
}

export interface ApiUsersGetRequestParams {
    pageIndex?: number;
    pageSize?: number;
}

export interface ApiUsersIdGetRequestParams {
    id: string;
}

export interface ApiUsersPostRequestParams {
    createUserCommand?: CreateUserCommand;
}

export interface ApiUsersPutRequestParams {
    updateUserCommand?: UpdateUserCommand;
}


export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersDelete(requestParameters: ApiUsersDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersFromAuthPut(requestParameters: ApiUsersFromAuthPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersGet(requestParameters: ApiUsersGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    apiUsersGetFromAuthGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdGet(requestParameters: ApiUsersIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersPost(requestParameters: ApiUsersPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersPut(requestParameters: ApiUsersPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
